### ISSUE TITLE
Changing directory with cd does not change to different drive.

### ISSUE THREAD

**Issue by jacobrillema** [narekmal/vscode-run-git-difftool#2]
I have my projects and repos listed under the F drive. VS Code is installed on the C drive. When it tries to "cd f:/projects" it will not work. If you add the /d option to the cd command it should work.

`var cmd = 'cd /d ' + dirName + ' & ' + 'git difftool ' + fileName;`

**Comment by narekmalk** [comment]
Added /d and now works when project is on different drive, thanks
